export const WALLPAPER_PATH = '/images/bliss-wallpaper.jpg';

export const APP_REGISTRY = [
  {
    id: 'my-computer',
    name: 'My Computer',
    iconPath: '/icons/my-computer.svg',
    type: 'system',
    componentName: 'MyComputer',
    defaultWidth: 600,
    defaultHeight: 400,
    showOnDesktop: true,
  },
  {
    id: 'recycle-bin',
    name: 'Recycle Bin',
    iconPath: '/icons/recycle-bin.svg',
    type: 'system',
    componentName: 'RecycleBin',
    defaultWidth: 600,
    defaultHeight: 400,
    showOnDesktop: true,
  },
  {
    id: 'internet-explorer',
    name: 'Internet Explorer',
    iconPath: '/icons/internet-explorer.svg',
    type: 'app',
    componentName: 'InternetExplorer',
    defaultWidth: 800,
    defaultHeight: 600,
    showOnDesktop: true,
  },
  {
    id: 'portfolio-folder',
    name: "Prasun's Portfolio",
    iconPath: '/icons/folder.svg',
    type: 'folder',
    componentName: 'PortfolioFolder',
    defaultWidth: 600,
    defaultHeight: 400,
    showOnDesktop: true,
    contents: ['resume-pdf', 'brt-report', 'ml-neuro-review', 'nsut-debate', '180dc-consulting'],
  },
  {
    id: 'resume-pdf',
    name: 'tech_Resume_exp_Prasun.pdf',
    iconPath: '/icons/pdf.svg',
    type: 'pdf',
    filePath: '/tech_Resume_exp_Prasun.pdf',
    defaultWidth: 750,
    defaultHeight: 650,
    showOnDesktop: true,
  },
  {
    id: 'brt-report',
    name: 'BRT_System_Delhi_Report.md',
    iconPath: '/icons/file.svg',
    type: 'file',
    componentName: 'MarkdownViewer',
    defaultWidth: 500,
    defaultHeight: 600,
    showOnDesktop: true,
  },
  {
    id: 'ml-neuro-review',
    name: 'Multimodal_ML_Neuro_Review.md',
    iconPath: '/icons/file.svg',
    type: 'file',
    componentName: 'MarkdownViewer',
    defaultWidth: 500,
    defaultHeight: 600,
    showOnDesktop: true,
    metadata: {
      authors: 'Vidit Pant & P Tarun'
    }
  },
  {
    id: 'nsut-debate',
    name: 'NSUT_Debating_Society.md',
    iconPath: '/icons/file.svg',
    type: 'file',
    componentName: 'MarkdownViewer',
    defaultWidth: 500,
    defaultHeight: 600,
    showOnDesktop: true,
  },
  {
    id: '180dc-consulting',
    name: '180DC_Consulting.md',
    iconPath: '/icons/file.svg',
    type: 'file',
    componentName: 'MarkdownViewer',
    defaultWidth: 500,
    defaultHeight: 600,
    showOnDesktop: true,
  }
];
